# Generated by Django 3.2.5 on 2021-07-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appartment',
            new_name='Apartment',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='appartment',
            new_name='apartment',
        ),
    ]
