# Generated by Django 3.2.5 on 2021-07-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210716_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
